project_id = "nzhiuplcxwooimrbdqba"

[functions.send-appointment-email]
verify_jwt = false

[functions.google-calendar-auth]
verify_jwt = false

[functions.google-calendar-sync]
verify_jwt = false

[functions.google-calendar-callback]
verify_jwt = false

[functions.google-calendar-disconnect]
verify_jwt = false

[functions.register-user]
verify_jwt = false

[functions.reset-user-password]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.ocr-id-card]
verify_jwt = false

[functions.register-with-invite]
verify_jwt = false
